"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.models.get_workout_count200_response import (
    GetWorkoutCount200Response,
)


class TestGetWorkoutCount200Response(unittest.TestCase):
    """GetWorkoutCount200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWorkoutCount200Response:
        """Test GetWorkoutCount200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetWorkoutCount200Response`
        """
        model = GetWorkoutCount200Response()
        if include_optional:
            return GetWorkoutCount200Response(
                workout_count = 56
            )
        else:
            return GetWorkoutCount200Response(
        )
        """

    def testGetWorkoutCount200Response(self):
        """Test GetWorkoutCount200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
