"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.models.get_workouts200_response import GetWorkouts200Response


class TestGetWorkouts200Response(unittest.TestCase):
    """GetWorkouts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWorkouts200Response:
        """Test GetWorkouts200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetWorkouts200Response`
        """
        model = GetWorkouts200Response()
        if include_optional:
            return GetWorkouts200Response(
                page = 1,
                page_count = 5,
                workouts = [
                    hevy_api_service.models.workout.Workout(
                        id = 'b459cba5-cd6d-463c-abd6-54f8eafcadcb', 
                        title = 'Morning Workout 💪', 
                        routine_id = 'b459cba5-cd6d-463c-abd6-54f8eafcadcb', 
                        description = 'Pushed myself to the limit today!', 
                        start_time = '2021-09-14T12:00:00Z', 
                        end_time = '2021-09-14T12:00:00Z', 
                        updated_at = '2021-09-14T12:00:00Z', 
                        created_at = '2021-09-14T12:00:00Z', 
                        exercises = [
                            hevy_api_service.models.workout_exercises_inner.Workout_exercises_inner(
                                index = 0, 
                                title = 'Bench Press (Barbell)', 
                                notes = 'Paid closer attention to form today. Felt great!', 
                                exercise_template_id = '05293BCA', 
                                supersets_id = 0, 
                                sets = [
                                    hevy_api_service.models.workout_exercises_inner_sets_inner.Workout_exercises_inner_sets_inner(
                                        index = 0, 
                                        type = 'normal', 
                                        weight_kg = 100, 
                                        reps = 10, 
                                        distance_meters = 1.337, 
                                        duration_seconds = 1.337, 
                                        rpe = 9.5, 
                                        custom_metric = 50, )
                                    ], )
                            ], )
                    ]
            )
        else:
            return GetWorkouts200Response(
        )
        """

    def testGetWorkouts200Response(self):
        """Test GetWorkouts200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
