"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.api.routines_api import RoutinesApi


class TestRoutinesApi(unittest.TestCase):
    """RoutinesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutinesApi()

    def tearDown(self) -> None:
        pass

    def test_create_routine(self) -> None:
        """Test case for create_routine

        Create a new routine
        """
        pass

    def test_get_routine_by_id(self) -> None:
        """Test case for get_routine_by_id

        Get a routine by its Id
        """
        pass

    def test_get_routines(self) -> None:
        """Test case for get_routines

        Get a paginated list of routines
        """
        pass

    def test_update_routine(self) -> None:
        """Test case for update_routine

        Update an existing routine
        """
        pass


if __name__ == "__main__":
    unittest.main()
