"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.models.put_routines_request_body import PutRoutinesRequestBody


class TestPutRoutinesRequestBody(unittest.TestCase):
    """PutRoutinesRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutRoutinesRequestBody:
        """Test PutRoutinesRequestBody
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PutRoutinesRequestBody`
        """
        model = PutRoutinesRequestBody()
        if include_optional:
            return PutRoutinesRequestBody(
                routine = hevy_api_service.models.put_routines_request_body_routine.PutRoutinesRequestBody_routine(
                    title = 'April Leg Day 🔥', 
                    notes = 'Focus on form over weight. Remember to stretch.', 
                    exercises = [
                        hevy_api_service.models.put_routines_request_exercise.PutRoutinesRequestExercise(
                            exercise_template_id = 'D04AC939', 
                            superset_id = 56, 
                            rest_seconds = 90, 
                            notes = 'Stay slow and controlled.', 
                            sets = [
                                hevy_api_service.models.put_routines_request_set.PutRoutinesRequestSet(
                                    type = 'normal', 
                                    weight_kg = 100, 
                                    reps = 10, 
                                    distance_meters = 56, 
                                    duration_seconds = 56, 
                                    custom_metric = 1.337, 
                                    rep_range = hevy_api_service.models.put_routines_request_set_rep_range.PutRoutinesRequestSet_rep_range(
                                        start = 8, 
                                        end = 12, ), )
                                ], )
                        ], )
            )
        else:
            return PutRoutinesRequestBody(
        )
        """

    def testPutRoutinesRequestBody(self):
        """Test PutRoutinesRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
