"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.api.exercise_templates_api import ExerciseTemplatesApi


class TestExerciseTemplatesApi(unittest.TestCase):
    """ExerciseTemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExerciseTemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_custom_exercise_template(self) -> None:
        """Test case for create_custom_exercise_template

        Create a new custom exercise template.
        """
        pass

    def test_get_exercise_template_by_id(self) -> None:
        """Test case for get_exercise_template_by_id

        Get a single exercise template by id.
        """
        pass

    def test_get_exercise_templates(self) -> None:
        """Test case for get_exercise_templates

        Get a paginated list of exercise templates available on the account.
        """
        pass


if __name__ == "__main__":
    unittest.main()
