"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.api.workouts_api import WorkoutsApi


class TestWorkoutsApi(unittest.TestCase):
    """WorkoutsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkoutsApi()

    def tearDown(self) -> None:
        pass

    def test_create_workout(self) -> None:
        """Test case for create_workout

        Create a new workout
        """
        pass

    def test_get_workout_by_id(self) -> None:
        """Test case for get_workout_by_id

        Get a single workout’s complete details by the workoutId
        """
        pass

    def test_get_workout_count(self) -> None:
        """Test case for get_workout_count

        Get the total number of workouts on the account
        """
        pass

    def test_get_workout_events(self) -> None:
        """Test case for get_workout_events

        Retrieve a paged list of workout events (updates or deletes) since a given date. Events are ordered from newest to oldest. The intention is to allow clients to keep their local cache of workouts up to date without having to fetch the entire list of workouts.
        """
        pass

    def test_get_workouts(self) -> None:
        """Test case for get_workouts

        Get a paginated list of workouts
        """
        pass

    def test_update_workout(self) -> None:
        """Test case for update_workout

        Update an existing workout
        """
        pass


if __name__ == "__main__":
    unittest.main()
