"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.models.get_exercise_history_exercise_template_id200_response import (
    GetExerciseHistoryExerciseTemplateId200Response,
)


class TestGetExerciseHistoryExerciseTemplateId200Response(unittest.TestCase):
    """GetExerciseHistoryExerciseTemplateId200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(
        self, include_optional
    ) -> GetExerciseHistoryExerciseTemplateId200Response:
        """Test GetExerciseHistoryExerciseTemplateId200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetExerciseHistoryExerciseTemplateId200Response`
        """
        model = GetExerciseHistoryExerciseTemplateId200Response()
        if include_optional:
            return GetExerciseHistoryExerciseTemplateId200Response(
                exercise_history = [
                    hevy_api_service.models.exercise_history_entry.ExerciseHistoryEntry(
                        workout_id = 'b459cba5-cd6d-463c-abd6-54f8eafcadcb', 
                        workout_title = 'Morning Workout 💪', 
                        workout_start_time = '2024-01-01T12:00:00Z', 
                        workout_end_time = '2024-01-01T13:00:00Z', 
                        exercise_template_id = 'D04AC939', 
                        weight_kg = 100, 
                        reps = 10, 
                        distance_meters = 56, 
                        duration_seconds = 56, 
                        rpe = 8.5, 
                        custom_metric = 1.337, 
                        set_type = 'normal', )
                    ]
            )
        else:
            return GetExerciseHistoryExerciseTemplateId200Response(
        )
        """

    def testGetExerciseHistoryExerciseTemplateId200Response(self):
        """Test GetExerciseHistoryExerciseTemplateId200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
