"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.api.routine_folders_api import RoutineFoldersApi


class TestRoutineFoldersApi(unittest.TestCase):
    """RoutineFoldersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutineFoldersApi()

    def tearDown(self) -> None:
        pass

    def test_create_routine_folder(self) -> None:
        """Test case for create_routine_folder

        Create a new routine folder. The folder will be created at index 0, and all other folders will have their indexes incremented.
        """
        pass

    def test_get_routine_folder_by_id(self) -> None:
        """Test case for get_routine_folder_by_id

        Get a single routine folder by id.
        """
        pass

    def test_get_routine_folders(self) -> None:
        """Test case for get_routine_folders

        Get a paginated list of routine folders available on the account.
        """
        pass


if __name__ == "__main__":
    unittest.main()
