"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from hevy_api_service.models.get_routines200_response import GetRoutines200Response


class TestGetRoutines200Response(unittest.TestCase):
    """GetRoutines200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRoutines200Response:
        """Test GetRoutines200Response
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `GetRoutines200Response`
        """
        model = GetRoutines200Response()
        if include_optional:
            return GetRoutines200Response(
                page = 1,
                page_count = 5,
                routines = [
                    hevy_api_service.models.routine.Routine(
                        id = 'b459cba5-cd6d-463c-abd6-54f8eafcadcb', 
                        title = 'Upper Body 💪', 
                        folder_id = 42, 
                        updated_at = '2021-09-14T12:00:00Z', 
                        created_at = '2021-09-14T12:00:00Z', 
                        exercises = [
                            hevy_api_service.models.routine_exercises_inner.Routine_exercises_inner(
                                index = 0, 
                                title = 'Bench Press (Barbell)', 
                                rest_seconds = '60', 
                                notes = 'Focus on form. Go down to 90 degrees.', 
                                exercise_template_id = '05293BCA', 
                                supersets_id = 0, 
                                sets = [
                                    hevy_api_service.models.routine_exercises_inner_sets_inner.Routine_exercises_inner_sets_inner(
                                        index = 0, 
                                        type = 'normal', 
                                        weight_kg = 100, 
                                        reps = 10, 
                                        rep_range = hevy_api_service.models.put_routines_request_set_rep_range.PutRoutinesRequestSet_rep_range(
                                            start = 8, 
                                            end = 12, ), 
                                        distance_meters = 1.337, 
                                        duration_seconds = 1.337, 
                                        rpe = 9.5, 
                                        custom_metric = 50, )
                                    ], )
                            ], )
                    ]
            )
        else:
            return GetRoutines200Response(
        )
        """

    def testGetRoutines200Response(self):
        """Test GetRoutines200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
