[tools]
python = "3.12.12"
uv = "0.10.7"
hk = "1.36.0"
ruff = "0.15.4"
pkl = "0.31.0"
taplo = "0.10.0"
yamlfmt = "0.21.0"
pinact = "3.9.0"
zizmor = "1.22.0"
github-cli = "2.86.0"
hadolint = "2.14.0"
watchexec = "2.5.0"
"npm:@quobix/vacuum" = "0.23.8"
"npm:@biomejs/biome" = "2.4.4"
"npm:dclint" = "3.1.0"
"trufflehog" = "3.93.6"
ty = "0.0.20"
