experimental_monorepo_root = true

[env]
'_'.file = { path = ".env" }
'_'.source = { path = ["scripts/ci/git-current.sh", ".env.sh"] }
DOCKER_BUILDKIT = 1
RP_AUTH_TOKEN = ""
MONOREPO_ROOT = "{{config_root}}"
[monorepo]
config_roots = ["packages/*", "scripts/*"]

[settings]
experimental = true
pipx.uvx = true
