name: kestra-stack
services:
  kestra:
    image: kestra/kestra:v1.2.8
    volumes:
      - type: volume
        source: kestra_data
        target: /app/storage
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: false
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: packages/pipeline/flows
        target: /app/flows
      - type: bind
        source: packages/pipeline/application.yml
        target: /app/confs/application.yml
    env_file:
      - path: .env.example
      - path: .env
        required: false
    ports:
      - target: 8080
        host_ip: 127.0.0.1
        published: 8080
        protocol: tcp
        mode: host
    command: server local --config /app/confs/application.yml
    restart: unless-stopped # Better than 'always' as it won't restart if manually stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    user: root
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    pull_policy: always

  redka:
    image: nalgeon/redka:1.0.1
    volumes:
      - type: bind
        source: ./data/redka
        target: /data
    ports:
      - target: 6379
        host_ip: 127.0.0.1
        published: 6379
        protocol: tcp
        mode: host
    command: [ "-h", "0.0.0.0", "-p", "6379", "/data/redka.db" ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "valkey-cli", "PING" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    pull_policy: always

volumes:
  kestra_data:
    name: kestra_persistence
    labels:
      description: "Persistent storage for Kestra flows and executions"
  redka_data:
    name: redka_persistence
    labels:
      description: "Persistent storage for Redka SQLite database"
