services:
  valkey:
    image: valkey/valkey:8-alpine
    volumes:
      - type: bind
        source: ./data/valkey
        target: /data
    ports:
      - target: 6379
        host_ip: 127.0.0.1
        published: 6379
        protocol: tcp
        mode: host
    command: ["valkey-server", "--save", "5", "1", "--loglevel", "warning"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    pull_policy: always
