"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr


class ActiveSubscription(BaseModel):
    """
    ActiveSubscription
    """  # noqa: E501

    platform: StrictStr | None = None
    iap_id: StrictInt | None = Field(default=None, alias="iapId")
    iap_purchase_type: StrictStr | None = Field(default=None, alias="iapPurchaseType")
    iap_platform_id: StrictStr | None = Field(default=None, alias="iapPlatformId")
    iap_name: StrictStr | None = Field(default=None, alias="iapName")
    is_free_trial: StrictBool | None = Field(default=None, alias="isFreeTrial")
    is_intro_priced: StrictBool | None = Field(default=None, alias="isIntroPriced")
    referral_id: StrictInt | None = Field(default=None, alias="referralId")
    referral_code: StrictStr | None = Field(default=None, alias="referralCode")
    referral_type: StrictStr | None = Field(default=None, alias="referralType")
    purchase_date: datetime | None = Field(default=None, alias="purchaseDate")
    expiration_date: datetime | None = Field(default=None, alias="expirationDate")
    cancellation_date: datetime | None = Field(default=None, alias="cancellationDate")
    access: list[StrictStr] | None = None
    subscription_id: StrictStr | None = Field(default=None, alias="subscriptionId")
    __properties: ClassVar[list[str]] = [
        "platform",
        "iapId",
        "iapPurchaseType",
        "iapPlatformId",
        "iapName",
        "isFreeTrial",
        "isIntroPriced",
        "referralId",
        "referralCode",
        "referralType",
        "purchaseDate",
        "expirationDate",
        "cancellationDate",
        "access",
        "subscriptionId",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ActiveSubscription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if referral_id (nullable) is None
        # and model_fields_set contains the field
        if self.referral_id is None and "referral_id" in self.model_fields_set:
            _dict["referralId"] = None

        # set to None if referral_code (nullable) is None
        # and model_fields_set contains the field
        if self.referral_code is None and "referral_code" in self.model_fields_set:
            _dict["referralCode"] = None

        # set to None if referral_type (nullable) is None
        # and model_fields_set contains the field
        if self.referral_type is None and "referral_type" in self.model_fields_set:
            _dict["referralType"] = None

        # set to None if cancellation_date (nullable) is None
        # and model_fields_set contains the field
        if (
            self.cancellation_date is None
            and "cancellation_date" in self.model_fields_set
        ):
            _dict["cancellationDate"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ActiveSubscription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "platform": obj.get("platform"),
                "iapId": obj.get("iapId"),
                "iapPurchaseType": obj.get("iapPurchaseType"),
                "iapPlatformId": obj.get("iapPlatformId"),
                "iapName": obj.get("iapName"),
                "isFreeTrial": obj.get("isFreeTrial"),
                "isIntroPriced": obj.get("isIntroPriced"),
                "referralId": obj.get("referralId"),
                "referralCode": obj.get("referralCode"),
                "referralType": obj.get("referralType"),
                "purchaseDate": obj.get("purchaseDate"),
                "expirationDate": obj.get("expirationDate"),
                "cancellationDate": obj.get("cancellationDate"),
                "access": obj.get("access"),
                "subscriptionId": obj.get("subscriptionId"),
            }
        )
        return _obj
