"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr

from api_service_rp.models.day_exercise import DayExercise


class Day(BaseModel):
    """
    Day
    """  # noqa: E501

    id: StrictInt | None = None
    meso_id: StrictInt | None = Field(default=None, alias="mesoId")
    week: StrictInt | None = None
    position: StrictInt | None = None
    bodyweight: StrictFloat | StrictInt | None = None
    bodyweight_at: datetime | None = Field(default=None, alias="bodyweightAt")
    unit: StrictStr | None = None
    label: StrictStr | None = None
    finished_at: datetime | None = Field(default=None, alias="finishedAt")
    status: StrictStr | None = None
    notes: list[dict[str, Any]] | None = None
    muscle_groups: list[dict[str, Any]] | None = Field(
        default=None, alias="muscleGroups"
    )
    exercises: list[DayExercise] | None = None
    __properties: ClassVar[list[str]] = [
        "id",
        "mesoId",
        "week",
        "position",
        "bodyweight",
        "bodyweightAt",
        "unit",
        "label",
        "finishedAt",
        "status",
        "notes",
        "muscleGroups",
        "exercises",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Day from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in exercises (list)
        _items = []
        if self.exercises:
            for _item_exercises in self.exercises:
                if _item_exercises:
                    _items.append(_item_exercises.to_dict())
            _dict["exercises"] = _items
        # set to None if bodyweight (nullable) is None
        # and model_fields_set contains the field
        if self.bodyweight is None and "bodyweight" in self.model_fields_set:
            _dict["bodyweight"] = None

        # set to None if bodyweight_at (nullable) is None
        # and model_fields_set contains the field
        if self.bodyweight_at is None and "bodyweight_at" in self.model_fields_set:
            _dict["bodyweightAt"] = None

        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict["finishedAt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Day from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "mesoId": obj.get("mesoId"),
                "week": obj.get("week"),
                "position": obj.get("position"),
                "bodyweight": obj.get("bodyweight"),
                "bodyweightAt": obj.get("bodyweightAt"),
                "unit": obj.get("unit"),
                "label": obj.get("label"),
                "finishedAt": obj.get("finishedAt"),
                "status": obj.get("status"),
                "notes": obj.get("notes"),
                "muscleGroups": obj.get("muscleGroups"),
                "exercises": [
                    DayExercise.from_dict(_item) for _item in obj["exercises"]
                ]
                if obj.get("exercises") is not None
                else None,
            }
        )
        return _obj
