"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr

from api_service_rp.models.exercise_set import ExerciseSet


class DayExercise(BaseModel):
    """
    DayExercise
    """  # noqa: E501

    id: StrictInt | None = None
    day_id: StrictInt | None = Field(default=None, alias="dayId")
    exercise_id: StrictInt | None = Field(default=None, alias="exerciseId")
    position: StrictInt | None = None
    joint_pain: StrictInt | None = Field(default=None, alias="jointPain")
    muscle_group_id: StrictInt | None = Field(default=None, alias="muscleGroupId")
    source_day_exercise_id: StrictInt | None = Field(
        default=None, alias="sourceDayExerciseId"
    )
    status: StrictStr | None = None
    sets: list[ExerciseSet] | None = None
    __properties: ClassVar[list[str]] = [
        "id",
        "dayId",
        "exerciseId",
        "position",
        "jointPain",
        "muscleGroupId",
        "sourceDayExerciseId",
        "status",
        "sets",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of DayExercise from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sets (list)
        _items = []
        if self.sets:
            for _item_sets in self.sets:
                if _item_sets:
                    _items.append(_item_sets.to_dict())
            _dict["sets"] = _items
        # set to None if joint_pain (nullable) is None
        # and model_fields_set contains the field
        if self.joint_pain is None and "joint_pain" in self.model_fields_set:
            _dict["jointPain"] = None

        # set to None if source_day_exercise_id (nullable) is None
        # and model_fields_set contains the field
        if (
            self.source_day_exercise_id is None
            and "source_day_exercise_id" in self.model_fields_set
        ):
            _dict["sourceDayExerciseId"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of DayExercise from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "dayId": obj.get("dayId"),
                "exerciseId": obj.get("exerciseId"),
                "position": obj.get("position"),
                "jointPain": obj.get("jointPain"),
                "muscleGroupId": obj.get("muscleGroupId"),
                "sourceDayExerciseId": obj.get("sourceDayExerciseId"),
                "status": obj.get("status"),
                "sets": [ExerciseSet.from_dict(_item) for _item in obj["sets"]]
                if obj.get("sets") is not None
                else None,
            }
        )
        return _obj
