"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr


class Exercise(BaseModel):
    """
    Exercise
    """  # noqa: E501

    id: StrictInt | None = None
    name: StrictStr | None = None
    muscle_group_id: StrictInt | None = Field(default=None, alias="muscleGroupId")
    mg_sub_type: StrictStr | None = Field(
        default=None, description='e.g. "vertical"', alias="mgSubType"
    )
    exercise_type: StrictStr | None = Field(default=None, alias="exerciseType")
    youtube_id: StrictStr | None = Field(default=None, alias="youtubeId")
    user_id: StrictInt | None = Field(
        default=None,
        description="null for built-in, user ID for custom",
        alias="userId",
    )
    notes: list[dict[str, Any]] | None = None
    created_at: datetime | None = Field(default=None, alias="createdAt")
    updated_at: datetime | None = Field(default=None, alias="updatedAt")
    deleted_at: datetime | None = Field(default=None, alias="deletedAt")
    __properties: ClassVar[list[str]] = [
        "id",
        "name",
        "muscleGroupId",
        "mgSubType",
        "exerciseType",
        "youtubeId",
        "userId",
        "notes",
        "createdAt",
        "updatedAt",
        "deletedAt",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of Exercise from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if mg_sub_type (nullable) is None
        # and model_fields_set contains the field
        if self.mg_sub_type is None and "mg_sub_type" in self.model_fields_set:
            _dict["mgSubType"] = None

        # set to None if youtube_id (nullable) is None
        # and model_fields_set contains the field
        if self.youtube_id is None and "youtube_id" in self.model_fields_set:
            _dict["youtubeId"] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict["userId"] = None

        # set to None if deleted_at (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_at is None and "deleted_at" in self.model_fields_set:
            _dict["deletedAt"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of Exercise from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "muscleGroupId": obj.get("muscleGroupId"),
                "mgSubType": obj.get("mgSubType"),
                "exerciseType": obj.get("exerciseType"),
                "youtubeId": obj.get("youtubeId"),
                "userId": obj.get("userId"),
                "notes": obj.get("notes"),
                "createdAt": obj.get("createdAt"),
                "updatedAt": obj.get("updatedAt"),
                "deletedAt": obj.get("deletedAt"),
            }
        )
        return _obj
