"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr


class ExerciseSet(BaseModel):
    """
    ExerciseSet
    """  # noqa: E501

    id: StrictInt | None = None
    day_exercise_id: StrictInt | None = Field(default=None, alias="dayExerciseId")
    position: StrictInt | None = None
    set_type: StrictStr | None = Field(default=None, alias="setType")
    weight: StrictFloat | StrictInt | None = None
    weight_target: StrictFloat | StrictInt | None = Field(
        default=None, alias="weightTarget"
    )
    weight_target_min: StrictFloat | StrictInt | None = Field(
        default=None, alias="weightTargetMin"
    )
    weight_target_max: StrictFloat | StrictInt | None = Field(
        default=None, alias="weightTargetMax"
    )
    reps: StrictInt | None = None
    reps_target: StrictInt | None = Field(default=None, alias="repsTarget")
    bodyweight: StrictFloat | StrictInt | None = None
    unit: StrictStr | None = None
    finished_at: datetime | None = Field(default=None, alias="finishedAt")
    status: StrictStr | None = None
    created_at: datetime | None = Field(default=None, alias="createdAt")
    __properties: ClassVar[list[str]] = [
        "id",
        "dayExerciseId",
        "position",
        "setType",
        "weight",
        "weightTarget",
        "weightTargetMin",
        "weightTargetMax",
        "reps",
        "repsTarget",
        "bodyweight",
        "unit",
        "finishedAt",
        "status",
        "createdAt",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ExerciseSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if weight (nullable) is None
        # and model_fields_set contains the field
        if self.weight is None and "weight" in self.model_fields_set:
            _dict["weight"] = None

        # set to None if weight_target (nullable) is None
        # and model_fields_set contains the field
        if self.weight_target is None and "weight_target" in self.model_fields_set:
            _dict["weightTarget"] = None

        # set to None if weight_target_min (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_target_min is None
            and "weight_target_min" in self.model_fields_set
        ):
            _dict["weightTargetMin"] = None

        # set to None if weight_target_max (nullable) is None
        # and model_fields_set contains the field
        if (
            self.weight_target_max is None
            and "weight_target_max" in self.model_fields_set
        ):
            _dict["weightTargetMax"] = None

        # set to None if reps (nullable) is None
        # and model_fields_set contains the field
        if self.reps is None and "reps" in self.model_fields_set:
            _dict["reps"] = None

        # set to None if reps_target (nullable) is None
        # and model_fields_set contains the field
        if self.reps_target is None and "reps_target" in self.model_fields_set:
            _dict["repsTarget"] = None

        # set to None if bodyweight (nullable) is None
        # and model_fields_set contains the field
        if self.bodyweight is None and "bodyweight" in self.model_fields_set:
            _dict["bodyweight"] = None

        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict["finishedAt"] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict["status"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ExerciseSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "dayExerciseId": obj.get("dayExerciseId"),
                "position": obj.get("position"),
                "setType": obj.get("setType"),
                "weight": obj.get("weight"),
                "weightTarget": obj.get("weightTarget"),
                "weightTargetMin": obj.get("weightTargetMin"),
                "weightTargetMax": obj.get("weightTargetMax"),
                "reps": obj.get("reps"),
                "repsTarget": obj.get("repsTarget"),
                "bodyweight": obj.get("bodyweight"),
                "unit": obj.get("unit"),
                "finishedAt": obj.get("finishedAt"),
                "status": obj.get("status"),
                "createdAt": obj.get("createdAt"),
            }
        )
        return _obj
