"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictStr

from api_service_rp.models.exercise_history_set import ExerciseHistorySet


class ExerciseHistoryInner(BaseModel):
    """
    ExerciseHistoryInner
    """  # noqa: E501

    name: StrictStr | None = Field(default=None, description="Mesocycle name")
    key: StrictStr | None = Field(default=None, description="Mesocycle key")
    set_groups: list[list[ExerciseHistorySet]] | None = Field(
        default=None, alias="setGroups"
    )
    __properties: ClassVar[list[str]] = ["name", "key", "setGroups"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ExerciseHistoryInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in set_groups (list of list)
        _items = []
        if self.set_groups:
            for _item_set_groups in self.set_groups:
                if _item_set_groups:
                    _items.append(
                        [
                            _inner_item.to_dict()
                            for _inner_item in _item_set_groups
                            if _inner_item is not None
                        ]
                    )
            _dict["setGroups"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ExerciseHistoryInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "name": obj.get("name"),
                "key": obj.get("key"),
                "setGroups": [
                    [ExerciseHistorySet.from_dict(_inner_item) for _inner_item in _item]
                    for _item in obj["setGroups"]
                ]
                if obj.get("setGroups") is not None
                else None,
            }
        )
        return _obj
