"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr


class UserAttributes(BaseModel):
    """
    UserAttributes
    """  # noqa: E501

    birthdate: StrictStr | None = Field(default=None, alias="BIRTHDATE")
    sex: StrictStr | None = Field(default=None, alias="SEX")
    training_years: StrictStr | None = Field(default=None, alias="TRAINING_YEARS")
    training_preference_exercise_types: StrictStr | None = Field(
        default=None,
        description="JSON-encoded string",
        alias="TRAINING_PREFERENCE_EXERCISE_TYPES",
    )
    attribution_survey: StrictStr | None = Field(
        default=None, alias="ATTRIBUTION_SURVEY"
    )
    created_on_platform: StrictStr | None = Field(
        default=None, alias="CREATED_ON_PLATFORM"
    )
    training_feature_auto_apply_weights: StrictBool | None = Field(
        default=None, alias="TRAINING_FEATURE_AUTO_APPLY_WEIGHTS"
    )
    training_apply_exercise_types: StrictBool | None = Field(
        default=None, alias="TRAINING_APPLY_EXERCISE_TYPES"
    )
    __properties: ClassVar[list[str]] = [
        "BIRTHDATE",
        "SEX",
        "TRAINING_YEARS",
        "TRAINING_PREFERENCE_EXERCISE_TYPES",
        "ATTRIBUTION_SURVEY",
        "CREATED_ON_PLATFORM",
        "TRAINING_FEATURE_AUTO_APPLY_WEIGHTS",
        "TRAINING_APPLY_EXERCISE_TYPES",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of UserAttributes from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of UserAttributes from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "BIRTHDATE": obj.get("BIRTHDATE"),
                "SEX": obj.get("SEX"),
                "TRAINING_YEARS": obj.get("TRAINING_YEARS"),
                "TRAINING_PREFERENCE_EXERCISE_TYPES": obj.get(
                    "TRAINING_PREFERENCE_EXERCISE_TYPES"
                ),
                "ATTRIBUTION_SURVEY": obj.get("ATTRIBUTION_SURVEY"),
                "CREATED_ON_PLATFORM": obj.get("CREATED_ON_PLATFORM"),
                "TRAINING_FEATURE_AUTO_APPLY_WEIGHTS": obj.get(
                    "TRAINING_FEATURE_AUTO_APPLY_WEIGHTS"
                ),
                "TRAINING_APPLY_EXERCISE_TYPES": obj.get(
                    "TRAINING_APPLY_EXERCISE_TYPES"
                ),
            }
        )
        return _obj
