"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictStr

from hevy_api_service.models.custom_exercise_type import CustomExerciseType
from hevy_api_service.models.equipment_category import EquipmentCategory
from hevy_api_service.models.muscle_group import MuscleGroup


class CreateCustomExerciseRequestBodyExercise(BaseModel):
    """
    CreateCustomExerciseRequestBodyExercise
    """  # noqa: E501

    title: StrictStr | None = Field(
        default=None, description="The title of the exercise template."
    )
    exercise_type: CustomExerciseType | None = None
    equipment_category: EquipmentCategory | None = Field(
        default=None, description="The equipment category of the exercise template."
    )
    muscle_group: MuscleGroup | None = Field(
        default=None, description="The muscle group of the exercise template."
    )
    other_muscles: list[MuscleGroup] | None = Field(
        default=None, description="The other muscles of the exercise template."
    )
    __properties: ClassVar[list[str]] = [
        "title",
        "exercise_type",
        "equipment_category",
        "muscle_group",
        "other_muscles",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of CreateCustomExerciseRequestBodyExercise from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of CreateCustomExerciseRequestBodyExercise from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "title": obj.get("title"),
                "exercise_type": obj.get("exercise_type"),
                "equipment_category": obj.get("equipment_category"),
                "muscle_group": obj.get("muscle_group"),
                "other_muscles": obj.get("other_muscles"),
            }
        )
        return _obj
