"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr


class ExerciseHistoryEntry(BaseModel):
    """
    ExerciseHistoryEntry
    """  # noqa: E501

    workout_id: StrictStr | None = Field(default=None, description="The workout ID")
    workout_title: StrictStr | None = Field(
        default=None, description="The workout title"
    )
    workout_start_time: StrictStr | None = Field(
        default=None,
        description="ISO 8601 timestamp of when the workout was recorded to have started.",
    )
    workout_end_time: StrictStr | None = Field(
        default=None,
        description="ISO 8601 timestamp of when the workout was recorded to have ended.",
    )
    exercise_template_id: StrictStr | None = Field(
        default=None, description="The exercise template ID"
    )
    weight_kg: StrictFloat | StrictInt | None = Field(
        default=None, description="The weight in kilograms"
    )
    reps: StrictInt | None = Field(
        default=None, description="The number of repetitions"
    )
    distance_meters: StrictInt | None = Field(
        default=None, description="The distance in meters"
    )
    duration_seconds: StrictInt | None = Field(
        default=None, description="The duration in seconds"
    )
    rpe: StrictFloat | StrictInt | None = Field(
        default=None, description="The Rating of Perceived Exertion"
    )
    custom_metric: StrictFloat | StrictInt | None = Field(
        default=None, description="A custom metric for the set"
    )
    set_type: StrictStr | None = Field(
        default=None, description="The type of set (warmup, normal, failure, dropset)"
    )
    __properties: ClassVar[list[str]] = [
        "workout_id",
        "workout_title",
        "workout_start_time",
        "workout_end_time",
        "exercise_template_id",
        "weight_kg",
        "reps",
        "distance_meters",
        "duration_seconds",
        "rpe",
        "custom_metric",
        "set_type",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ExerciseHistoryEntry from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if weight_kg (nullable) is None
        # and model_fields_set contains the field
        if self.weight_kg is None and "weight_kg" in self.model_fields_set:
            _dict["weight_kg"] = None

        # set to None if reps (nullable) is None
        # and model_fields_set contains the field
        if self.reps is None and "reps" in self.model_fields_set:
            _dict["reps"] = None

        # set to None if distance_meters (nullable) is None
        # and model_fields_set contains the field
        if self.distance_meters is None and "distance_meters" in self.model_fields_set:
            _dict["distance_meters"] = None

        # set to None if duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if (
            self.duration_seconds is None
            and "duration_seconds" in self.model_fields_set
        ):
            _dict["duration_seconds"] = None

        # set to None if rpe (nullable) is None
        # and model_fields_set contains the field
        if self.rpe is None and "rpe" in self.model_fields_set:
            _dict["rpe"] = None

        # set to None if custom_metric (nullable) is None
        # and model_fields_set contains the field
        if self.custom_metric is None and "custom_metric" in self.model_fields_set:
            _dict["custom_metric"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ExerciseHistoryEntry from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "workout_id": obj.get("workout_id"),
                "workout_title": obj.get("workout_title"),
                "workout_start_time": obj.get("workout_start_time"),
                "workout_end_time": obj.get("workout_end_time"),
                "exercise_template_id": obj.get("exercise_template_id"),
                "weight_kg": obj.get("weight_kg"),
                "reps": obj.get("reps"),
                "distance_meters": obj.get("distance_meters"),
                "duration_seconds": obj.get("duration_seconds"),
                "rpe": obj.get("rpe"),
                "custom_metric": obj.get("custom_metric"),
                "set_type": obj.get("set_type"),
            }
        )
        return _obj
