"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
from enum import Enum
from typing import Self


class MuscleGroup(str, Enum):
    """
    MuscleGroup
    """

    """
    allowed enum values
    """
    ABDOMINALS = "abdominals"
    SHOULDERS = "shoulders"
    BICEPS = "biceps"
    TRICEPS = "triceps"
    FOREARMS = "forearms"
    QUADRICEPS = "quadriceps"
    HAMSTRINGS = "hamstrings"
    CALVES = "calves"
    GLUTES = "glutes"
    ABDUCTORS = "abductors"
    ADDUCTORS = "adductors"
    LATS = "lats"
    UPPER_BACK = "upper_back"
    TRAPS = "traps"
    LOWER_BACK = "lower_back"
    CHEST = "chest"
    CARDIO = "cardio"
    NECK = "neck"
    FULL_BODY = "full_body"
    OTHER = "other"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MuscleGroup from a JSON string"""
        return cls(json.loads(json_str))
