"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
from typing import Any, Self

from pydantic import (
    BaseModel,
    ConfigDict,
    ValidationError,
    field_validator,
)

from hevy_api_service.models.deleted_workout import DeletedWorkout
from hevy_api_service.models.updated_workout import UpdatedWorkout

PAGINATEDWORKOUTEVENTSEVENTSINNER_ONE_OF_SCHEMAS = ["DeletedWorkout", "UpdatedWorkout"]


class PaginatedWorkoutEventsEventsInner(BaseModel):
    """
    PaginatedWorkoutEventsEventsInner
    """

    # data type: UpdatedWorkout
    oneof_schema_1_validator: UpdatedWorkout | None = None
    # data type: DeletedWorkout
    oneof_schema_2_validator: DeletedWorkout | None = None
    actual_instance: DeletedWorkout | UpdatedWorkout | None = None
    one_of_schemas: set[str] = {"DeletedWorkout", "UpdatedWorkout"}

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError(
                    "If a position argument is used, only 1 is allowed to set `actual_instance`"
                )
            if kwargs:
                raise ValueError(
                    "If a position argument is used, keyword arguments cannot be used."
                )
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator("actual_instance")
    def actual_instance_must_validate_oneof(cls, v):
        instance = PaginatedWorkoutEventsEventsInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: UpdatedWorkout
        if not isinstance(v, UpdatedWorkout):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `UpdatedWorkout`"
            )
        else:
            match += 1
        # validate data type: DeletedWorkout
        if not isinstance(v, DeletedWorkout):
            error_messages.append(
                f"Error! Input type `{type(v)}` is not `DeletedWorkout`"
            )
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when setting `actual_instance` in PaginatedWorkoutEventsEventsInner with oneOf schemas: DeletedWorkout, UpdatedWorkout. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when setting `actual_instance` in PaginatedWorkoutEventsEventsInner with oneOf schemas: DeletedWorkout, UpdatedWorkout. Details: "
                + ", ".join(error_messages)
            )
        else:
            return v

    @classmethod
    def from_dict(cls, obj: str | dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into UpdatedWorkout
        try:
            instance.actual_instance = UpdatedWorkout.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into DeletedWorkout
        try:
            instance.actual_instance = DeletedWorkout.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError(
                "Multiple matches found when deserializing the JSON string into PaginatedWorkoutEventsEventsInner with oneOf schemas: DeletedWorkout, UpdatedWorkout. Details: "
                + ", ".join(error_messages)
            )
        elif match == 0:
            # no match
            raise ValueError(
                "No match found when deserializing the JSON string into PaginatedWorkoutEventsEventsInner with oneOf schemas: DeletedWorkout, UpdatedWorkout. Details: "
                + ", ".join(error_messages)
            )
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(
            self.actual_instance.to_json
        ):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> dict[str, Any] | DeletedWorkout | UpdatedWorkout | None:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(
            self.actual_instance.to_dict
        ):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())
