"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr

from hevy_api_service.models.post_routines_request_exercise import (
    PostRoutinesRequestExercise,
)


class PostRoutinesRequestBodyRoutine(BaseModel):
    """
    PostRoutinesRequestBodyRoutine
    """  # noqa: E501

    title: StrictStr | None = Field(
        default=None, description="The title of the routine."
    )
    folder_id: StrictFloat | StrictInt | None = Field(
        default=None,
        description='The folder id the routine should be added to. Pass null to insert the routine into default "My Routines" folder',
    )
    notes: StrictStr | None = Field(
        default=None, description="Additional notes for the routine."
    )
    exercises: list[PostRoutinesRequestExercise] | None = None
    __properties: ClassVar[list[str]] = ["title", "folder_id", "notes", "exercises"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PostRoutinesRequestBodyRoutine from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in exercises (list)
        _items = []
        if self.exercises:
            for _item_exercises in self.exercises:
                if _item_exercises:
                    _items.append(_item_exercises.to_dict())
            _dict["exercises"] = _items
        # set to None if folder_id (nullable) is None
        # and model_fields_set contains the field
        if self.folder_id is None and "folder_id" in self.model_fields_set:
            _dict["folder_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PostRoutinesRequestBodyRoutine from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "title": obj.get("title"),
                "folder_id": obj.get("folder_id"),
                "notes": obj.get("notes"),
                "exercises": [
                    PostRoutinesRequestExercise.from_dict(_item)
                    for _item in obj["exercises"]
                ]
                if obj.get("exercises") is not None
                else None,
            }
        )
        return _obj
