"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Self

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictFloat,
    StrictInt,
    StrictStr,
    field_validator,
)

from hevy_api_service.models.post_routines_request_set_rep_range import (
    PostRoutinesRequestSetRepRange,
)


class PostRoutinesRequestSet(BaseModel):
    """
    PostRoutinesRequestSet
    """  # noqa: E501

    type: StrictStr | None = Field(default=None, description="The type of the set.")
    weight_kg: StrictFloat | StrictInt | None = Field(
        default=None, description="The weight in kilograms."
    )
    reps: StrictInt | None = Field(
        default=None, description="The number of repetitions."
    )
    distance_meters: StrictInt | None = Field(
        default=None, description="The distance in meters."
    )
    duration_seconds: StrictInt | None = Field(
        default=None, description="The duration in seconds."
    )
    custom_metric: StrictFloat | StrictInt | None = Field(
        default=None,
        description="A custom metric for the set. Currently used for steps and floors.",
    )
    rep_range: PostRoutinesRequestSetRepRange | None = None
    __properties: ClassVar[list[str]] = [
        "type",
        "weight_kg",
        "reps",
        "distance_meters",
        "duration_seconds",
        "custom_metric",
        "rep_range",
    ]

    @field_validator("type")
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["warmup", "normal", "failure", "dropset"]):
            raise ValueError(
                "must be one of enum values ('warmup', 'normal', 'failure', 'dropset')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of PostRoutinesRequestSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of rep_range
        if self.rep_range:
            _dict["rep_range"] = self.rep_range.to_dict()
        # set to None if weight_kg (nullable) is None
        # and model_fields_set contains the field
        if self.weight_kg is None and "weight_kg" in self.model_fields_set:
            _dict["weight_kg"] = None

        # set to None if reps (nullable) is None
        # and model_fields_set contains the field
        if self.reps is None and "reps" in self.model_fields_set:
            _dict["reps"] = None

        # set to None if distance_meters (nullable) is None
        # and model_fields_set contains the field
        if self.distance_meters is None and "distance_meters" in self.model_fields_set:
            _dict["distance_meters"] = None

        # set to None if duration_seconds (nullable) is None
        # and model_fields_set contains the field
        if (
            self.duration_seconds is None
            and "duration_seconds" in self.model_fields_set
        ):
            _dict["duration_seconds"] = None

        # set to None if custom_metric (nullable) is None
        # and model_fields_set contains the field
        if self.custom_metric is None and "custom_metric" in self.model_fields_set:
            _dict["custom_metric"] = None

        # set to None if rep_range (nullable) is None
        # and model_fields_set contains the field
        if self.rep_range is None and "rep_range" in self.model_fields_set:
            _dict["rep_range"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of PostRoutinesRequestSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "type": obj.get("type"),
                "weight_kg": obj.get("weight_kg"),
                "reps": obj.get("reps"),
                "distance_meters": obj.get("distance_meters"),
                "duration_seconds": obj.get("duration_seconds"),
                "custom_metric": obj.get("custom_metric"),
                "rep_range": PostRoutinesRequestSetRepRange.from_dict(obj["rep_range"])
                if obj.get("rep_range") is not None
                else None,
            }
        )
        return _obj
