[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/cli/Dockerfile"
watchPatterns = [
  "packages/cli/**",
  "packages/api-service/**",
  "packages/embeddings/**",
  "uv.lock",
]

[deploy]
startCommand = "rp-to-hevy-cli hevy export --type all -o s3://stashed-lockerbox-flrz0lt/exports/hevy/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
cronSchedule = "*/15 * * * *"
