[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/cli/Dockerfile"
watchPatterns = [
  "packages/cli/**",
  "packages/api-service/**",
  "packages/embeddings/**",
  "uv.lock",
  "railway/hevy-export.toml",
]

[deploy]
startCommand = "bash -c 'rp-to-hevy-cli hevy export --type all -o s3://stashed-lockerbox-flrz0lt/exports/hevy/'"

cronSchedule = "*/15 * * * *"
limitOverride.containers.cpu = 0.5
limitOverride.containers.memoryBytes = 1073741824
