[build]
builder = "DOCKERFILE"
dockerfilePath = "packages/cli/Dockerfile"
watchPatterns = [
  "packages/cli/**",
  "packages/api-service/**",
  "packages/embeddings/**",
  "uv.lock",
  "railway/rp-export.toml",
]

[deploy]
startCommand = 'rp-to-hevy-cli rp --type all -o s3://stashed-lockerbox-flrz0lt/exports/rp/'
cronSchedule = "*/15 * * * *"
limitOverride.containers.cpu = 0.5
limitOverride.containers.memoryBytes = 1073741824
