"""
Hevy API Docs

       Welcome to Hevy's public API! We're just starting to roll this out and depending on your       feedback, we'll be adding more features and endpoints. Also, we make no guarantees that        we won't completely change the structure or abandon the project entirely so use it at       your own risk. Currently, this API is only available to Hevy Pro users. You can get your        key on our web app at https://hevy.com/settings?developer. If you have any questions,       please reach out to pedro@hevyapp.com 🤝.

The version of the OpenAPI document: 0.0.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from datetime import datetime
from typing import Annotated, Any
from uuid import UUID

from pydantic import Field, StrictFloat, StrictInt, StrictStr, validate_call

from hevy_api_service.api_client import ApiClient, RequestSerialized
from hevy_api_service.api_response import ApiResponse
from hevy_api_service.models.get_exercise_history_exercise_template_id200_response import (
    GetExerciseHistoryExerciseTemplateId200Response,
)
from hevy_api_service.rest import RESTResponseType


class ExerciseHistoryApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_call
    async def get_exercise_history_exercise_template_id(
        self,
        api_key: UUID,
        exercise_template_id: Annotated[
            StrictStr, Field(description="The id of the exercise template")
        ],
        start_date: Annotated[
            datetime | None,
            Field(
                description="Optional start date for filtering exercise history (ISO 8601 format)"
            ),
        ] = None,
        end_date: Annotated[
            datetime | None,
            Field(
                description="Optional end date for filtering exercise history (ISO 8601 format)"
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[
            Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
        ] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetExerciseHistoryExerciseTemplateId200Response:
        """Get exercise history for a specific exercise template


        :param api_key: (required)
        :type api_key: UUID
        :param exercise_template_id: The id of the exercise template (required)
        :type exercise_template_id: str
        :param start_date: Optional start date for filtering exercise history (ISO 8601 format)
        :type start_date: datetime
        :param end_date: Optional end date for filtering exercise history (ISO 8601 format)
        :type end_date: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_exercise_history_exercise_template_id_serialize(
            api_key=api_key,
            exercise_template_id=exercise_template_id,
            start_date=start_date,
            end_date=end_date,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "GetExerciseHistoryExerciseTemplateId200Response",
            "400": None,
        }
        response_data = await self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data

    @validate_call
    async def get_exercise_history_exercise_template_id_with_http_info(
        self,
        api_key: UUID,
        exercise_template_id: Annotated[
            StrictStr, Field(description="The id of the exercise template")
        ],
        start_date: Annotated[
            datetime | None,
            Field(
                description="Optional start date for filtering exercise history (ISO 8601 format)"
            ),
        ] = None,
        end_date: Annotated[
            datetime | None,
            Field(
                description="Optional end date for filtering exercise history (ISO 8601 format)"
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[
            Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
        ] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetExerciseHistoryExerciseTemplateId200Response]:
        """Get exercise history for a specific exercise template


        :param api_key: (required)
        :type api_key: UUID
        :param exercise_template_id: The id of the exercise template (required)
        :type exercise_template_id: str
        :param start_date: Optional start date for filtering exercise history (ISO 8601 format)
        :type start_date: datetime
        :param end_date: Optional end date for filtering exercise history (ISO 8601 format)
        :type end_date: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_exercise_history_exercise_template_id_serialize(
            api_key=api_key,
            exercise_template_id=exercise_template_id,
            start_date=start_date,
            end_date=end_date,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "GetExerciseHistoryExerciseTemplateId200Response",
            "400": None,
        }
        response_data = await self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )

    @validate_call
    async def get_exercise_history_exercise_template_id_without_preload_content(
        self,
        api_key: UUID,
        exercise_template_id: Annotated[
            StrictStr, Field(description="The id of the exercise template")
        ],
        start_date: Annotated[
            datetime | None,
            Field(
                description="Optional start date for filtering exercise history (ISO 8601 format)"
            ),
        ] = None,
        end_date: Annotated[
            datetime | None,
            Field(
                description="Optional end date for filtering exercise history (ISO 8601 format)"
            ),
        ] = None,
        _request_timeout: None
        | Annotated[StrictFloat, Field(gt=0)]
        | tuple[
            Annotated[StrictFloat, Field(gt=0)], Annotated[StrictFloat, Field(gt=0)]
        ] = None,
        _request_auth: dict[StrictStr, Any] | None = None,
        _content_type: StrictStr | None = None,
        _headers: dict[StrictStr, Any] | None = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get exercise history for a specific exercise template


        :param api_key: (required)
        :type api_key: UUID
        :param exercise_template_id: The id of the exercise template (required)
        :type exercise_template_id: str
        :param start_date: Optional start date for filtering exercise history (ISO 8601 format)
        :type start_date: datetime
        :param end_date: Optional end date for filtering exercise history (ISO 8601 format)
        :type end_date: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """  # noqa: E501

        _param = self._get_exercise_history_exercise_template_id_serialize(
            api_key=api_key,
            exercise_template_id=exercise_template_id,
            start_date=start_date,
            end_date=end_date,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index,
        )

        _response_types_map: dict[str, str | None] = {
            "200": "GetExerciseHistoryExerciseTemplateId200Response",
            "400": None,
        }
        response_data = await self.api_client.call_api(
            *_param, _request_timeout=_request_timeout
        )
        return response_data.response

    def _get_exercise_history_exercise_template_id_serialize(
        self,
        api_key,
        exercise_template_id,
        start_date,
        end_date,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: dict[str, str] = {}

        _path_params: dict[str, str] = {}
        _query_params: list[tuple[str, str]] = []
        _header_params: dict[str, str | None] = _headers or {}
        _form_params: list[tuple[str, str]] = []
        _files: dict[
            str, str | bytes | list[str] | list[bytes] | list[tuple[str, bytes]]
        ] = {}
        _body_params: bytes | None = None

        # process the path parameters
        if exercise_template_id is not None:
            _path_params["exerciseTemplateId"] = exercise_template_id
        # process the query parameters
        if start_date is not None:
            if isinstance(start_date, datetime):
                _query_params.append(
                    (
                        "start_date",
                        start_date.strftime(
                            self.api_client.configuration.datetime_format
                        ),
                    )
                )
            else:
                _query_params.append(("start_date", start_date))

        if end_date is not None:
            if isinstance(end_date, datetime):
                _query_params.append(
                    (
                        "end_date",
                        end_date.strftime(
                            self.api_client.configuration.datetime_format
                        ),
                    )
                )
            else:
                _query_params.append(("end_date", end_date))

        # process the header parameters
        if api_key is not None:
            _header_params["api-key"] = api_key
        # process the form parameters
        # process the body parameter

        # set the HTTP header `Accept`
        if "Accept" not in _header_params:
            _header_params["Accept"] = self.api_client.select_header_accept(
                ["application/json"]
            )

        # authentication setting
        _auth_settings: list[str] = []

        return self.api_client.param_serialize(
            method="GET",
            resource_path="/v1/exercise_history/{exerciseTemplateId}",
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth,
        )
