"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.active_subscription import ActiveSubscription


class TestActiveSubscription(unittest.TestCase):
    """ActiveSubscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActiveSubscription:
        """Test ActiveSubscription
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ActiveSubscription`
        """
        model = ActiveSubscription()
        if include_optional:
            return ActiveSubscription(
                platform = '',
                iap_id = 56,
                iap_purchase_type = '',
                iap_platform_id = '',
                iap_name = '',
                is_free_trial = True,
                is_intro_priced = True,
                referral_id = 56,
                referral_code = '',
                referral_type = '',
                purchase_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                cancellation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                access = [
                    ''
                    ],
                subscription_id = ''
            )
        else:
            return ActiveSubscription(
        )
        """

    def testActiveSubscription(self):
        """Test ActiveSubscription"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
