"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.api.user_api import UserApi


class TestUserApi(unittest.IsolatedAsyncioTestCase):
    """UserApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UserApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_user_profile(self) -> None:
        """Test case for get_user_profile

        Get user profile
        """
        pass

    async def test_get_user_subscriptions(self) -> None:
        """Test case for get_user_subscriptions

        Get user subscriptions
        """
        pass

    async def test_update_user_profile(self) -> None:
        """Test case for update_user_profile

        Update user profile
        """
        pass


if __name__ == "__main__":
    unittest.main()
