"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.user_profile import UserProfile


class TestUserProfile(unittest.TestCase):
    """UserProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserProfile:
        """Test UserProfile
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserProfile`
        """
        model = UserProfile()
        if include_optional:
            return UserProfile(
                id = 56,
                email = '',
                display_name = '',
                photo_url = '',
                google_id = '',
                apple_id = '',
                facebook_id = '',
                role_id = 56,
                stripe_id = '',
                klaviyo_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                first_seen_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                attributes = api_service_rp.models.user_attributes.UserAttributes(
                    birthdate = '', 
                    sex = '', 
                    training_years = '', 
                    training_preference_exercise_types = '', 
                    attribution_survey = '', 
                    created_on_platform = '', 
                    training_feature_auto_apply_weights = True, 
                    training_apply_exercise_types = True, )
            )
        else:
            return UserProfile(
        )
        """

    def testUserProfile(self):
        """Test UserProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
