"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.api.app_api import AppApi


class TestAppApi(unittest.IsolatedAsyncioTestCase):
    """AppApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AppApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_app_config(self) -> None:
        """Test case for get_app_config

        Get app config
        """
        pass

    async def test_get_products(self) -> None:
        """Test case for get_products

        Get product catalog
        """
        pass

    async def test_get_user_review(self) -> None:
        """Test case for get_user_review

        Get user review data
        """
        pass

    async def test_get_web_manifest(self) -> None:
        """Test case for get_web_manifest

        Get PWA web manifest
        """
        pass

    async def test_submit_user_review(self) -> None:
        """Test case for submit_user_review

        Submit user review
        """
        pass


if __name__ == "__main__":
    unittest.main()
