"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.muscle_group_priority import MuscleGroupPriority


class TestMuscleGroupPriority(unittest.TestCase):
    """MuscleGroupPriority unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MuscleGroupPriority:
        """Test MuscleGroupPriority
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `MuscleGroupPriority`
        """
        model = MuscleGroupPriority()
        if include_optional:
            return MuscleGroupPriority(
                id = 56,
                muscle_group_id = 56,
                mg_priority_type = ''
            )
        else:
            return MuscleGroupPriority(
        )
        """

    def testMuscleGroupPriority(self):
        """Test MuscleGroupPriority"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
