"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.mesocycle import Mesocycle


class TestMesocycle(unittest.TestCase):
    """Mesocycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Mesocycle:
        """Test Mesocycle
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Mesocycle`
        """
        model = Mesocycle()
        if include_optional:
            return Mesocycle(
                id = 56,
                key = '',
                user_id = 56,
                name = '',
                days = 56,
                unit = '',
                week_count = 56,
                source_template_id = 56,
                source_meso_id = 56,
                micro_rirs = 56,
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                first_set_completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_workout_finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                priorities = {
                    'key' : api_service_rp.models.muscle_group_priority.MuscleGroupPriority(
                        id = 56, 
                        muscle_group_id = 56, 
                        mg_priority_type = '', )
                    },
                notes = [
                    None
                    ],
                status = '',
                generated_from = '',
                weeks = [
                    api_service_rp.models.week.Week(
                        days = [
                            api_service_rp.models.day.Day(
                                id = 56, 
                                meso_id = 56, 
                                week = 56, 
                                position = 56, 
                                bodyweight = 1.337, 
                                bodyweight_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                unit = '', 
                                label = '', 
                                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                status = '', 
                                notes = [
                                    None
                                    ], 
                                muscle_groups = [
                                    None
                                    ], 
                                exercises = [
                                    api_service_rp.models.day_exercise.DayExercise(
                                        id = 56, 
                                        day_id = 56, 
                                        exercise_id = 56, 
                                        position = 56, 
                                        joint_pain = 56, 
                                        muscle_group_id = 56, 
                                        source_day_exercise_id = 56, 
                                        status = '', 
                                        sets = [
                                            api_service_rp.models.exercise_set.ExerciseSet(
                                                id = 56, 
                                                day_exercise_id = 56, 
                                                position = 56, 
                                                set_type = '', 
                                                weight = 1.337, 
                                                weight_target = 1.337, 
                                                weight_target_min = 1.337, 
                                                weight_target_max = 1.337, 
                                                reps = 56, 
                                                reps_target = 56, 
                                                bodyweight = 1.337, 
                                                unit = '', 
                                                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                                status = '', 
                                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                            ], )
                                    ], )
                            ], )
                    ]
            )
        else:
            return Mesocycle(
        )
        """

    def testMesocycle(self):
        """Test Mesocycle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
