"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.user_subscriptions import UserSubscriptions


class TestUserSubscriptions(unittest.TestCase):
    """UserSubscriptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSubscriptions:
        """Test UserSubscriptions
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserSubscriptions`
        """
        model = UserSubscriptions()
        if include_optional:
            return UserSubscriptions(
                active_subscriptions = [
                    api_service_rp.models.active_subscription.ActiveSubscription(
                        platform = '', 
                        iap_id = 56, 
                        iap_purchase_type = '', 
                        iap_platform_id = '', 
                        iap_name = '', 
                        is_free_trial = True, 
                        is_intro_priced = True, 
                        referral_id = 56, 
                        referral_code = '', 
                        referral_type = '', 
                        purchase_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        cancellation_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        access = [
                            ''
                            ], 
                        subscription_id = '', )
                    ],
                consumed_iaps = [
                    api_service_rp.models.consumed_iap.ConsumedIap(
                        platform = '', 
                        purchase_type = '', 
                        platform_id = '', 
                        subscription_group_id = '', 
                        subscription_group_key = '', 
                        access = [
                            ''
                            ], 
                        access_ends_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                stripe_ids = [
                    ''
                    ],
                training_last_access_added_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return UserSubscriptions(
        )
        """

    def testUserSubscriptions(self):
        """Test UserSubscriptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
