"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.user_attributes import UserAttributes


class TestUserAttributes(unittest.TestCase):
    """UserAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserAttributes:
        """Test UserAttributes
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `UserAttributes`
        """
        model = UserAttributes()
        if include_optional:
            return UserAttributes(
                birthdate = '',
                sex = '',
                training_years = '',
                training_preference_exercise_types = '',
                attribution_survey = '',
                created_on_platform = '',
                training_feature_auto_apply_weights = True,
                training_apply_exercise_types = True
            )
        else:
            return UserAttributes(
        )
        """

    def testUserAttributes(self):
        """Test UserAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
