"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.day_exercise import DayExercise


class TestDayExercise(unittest.TestCase):
    """DayExercise unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DayExercise:
        """Test DayExercise
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DayExercise`
        """
        model = DayExercise()
        if include_optional:
            return DayExercise(
                id = 56,
                day_id = 56,
                exercise_id = 56,
                position = 56,
                joint_pain = 56,
                muscle_group_id = 56,
                source_day_exercise_id = 56,
                status = '',
                sets = [
                    api_service_rp.models.exercise_set.ExerciseSet(
                        id = 56, 
                        day_exercise_id = 56, 
                        position = 56, 
                        set_type = '', 
                        weight = 1.337, 
                        weight_target = 1.337, 
                        weight_target_min = 1.337, 
                        weight_target_max = 1.337, 
                        reps = 56, 
                        reps_target = 56, 
                        bodyweight = 1.337, 
                        unit = '', 
                        finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        status = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return DayExercise(
        )
        """

    def testDayExercise(self):
        """Test DayExercise"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
