"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.api.training_data_api import TrainingDataApi


class TestTrainingDataApi(unittest.IsolatedAsyncioTestCase):
    """TrainingDataApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = TrainingDataApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_bootstrap(self) -> None:
        """Test case for get_bootstrap

        Get bootstrap data
        """
        pass

    async def test_get_exercise_history(self) -> None:
        """Test case for get_exercise_history

        Get exercise history
        """
        pass

    async def test_get_exercises(self) -> None:
        """Test case for get_exercises

        Get all exercises
        """
        pass

    async def test_get_mesocycle(self) -> None:
        """Test case for get_mesocycle

        Get full mesocycle detail
        """
        pass

    async def test_get_mesocycles(self) -> None:
        """Test case for get_mesocycles

        List all mesocycles
        """
        pass

    async def test_get_second_meso_meta(self) -> None:
        """Test case for get_second_meso_meta

        Get second mesocycle meta info
        """
        pass

    async def test_get_template(self) -> None:
        """Test case for get_template

        Get a specific template
        """
        pass

    async def test_get_templates(self) -> None:
        """Test case for get_templates

        Get all templates
        """
        pass

    async def test_get_user_exercise_history(self) -> None:
        """Test case for get_user_exercise_history

        Get user exercise history
        """
        pass


if __name__ == "__main__":
    unittest.main()
