"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.consumed_iap import ConsumedIap


class TestConsumedIap(unittest.TestCase):
    """ConsumedIap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConsumedIap:
        """Test ConsumedIap
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ConsumedIap`
        """
        model = ConsumedIap()
        if include_optional:
            return ConsumedIap(
                platform = '',
                purchase_type = '',
                platform_id = '',
                subscription_group_id = '',
                subscription_group_key = '',
                access = [
                    ''
                    ],
                access_ends_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ConsumedIap(
        )
        """

    def testConsumedIap(self):
        """Test ConsumedIap"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
