"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.models.second_meso_meta import SecondMesoMeta


class TestSecondMesoMeta(unittest.TestCase):
    """SecondMesoMeta unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SecondMesoMeta:
        """Test SecondMesoMeta
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `SecondMesoMeta`
        """
        model = SecondMesoMeta()
        if include_optional:
            return SecondMesoMeta(
                key = '',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return SecondMesoMeta(
        )
        """

    def testSecondMesoMeta(self):
        """Test SecondMesoMeta"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
