"""
RP Strength Training API

RP Strength Training API for workout data, user profiles, subscriptions, and training management.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from api_service_rp.api.purchases_api import PurchasesApi


class TestPurchasesApi(unittest.IsolatedAsyncioTestCase):
    """PurchasesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = PurchasesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_complete_purchase(self) -> None:
        """Test case for complete_purchase

        Complete a purchase
        """
        pass

    async def test_enter_referral(self) -> None:
        """Test case for enter_referral

        Enter a referral code
        """
        pass

    async def test_start_checkout(self) -> None:
        """Test case for start_checkout

        Start checkout flow
        """
        pass

    async def test_verify_transactions(self) -> None:
        """Test case for verify_transactions

        Verify IAP transactions
        """
        pass


if __name__ == "__main__":
    unittest.main()
