[env]
RP_APP_BASE_URL = "https://training.rpstrength.com/api"
HEVY_API_BASE_URL = "https://api.hevyapp.com"
RP_APP_VERSION = "1.1.13"
IMAGE_NAME = "rp-to-hevy-cli"

[tasks.build]
env = { '_'.source = { path = "../../github-token.env.sh" } }
run = "docker buildx build --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN -f Dockerfile -t $IMAGE_NAME ../.."
description = "Build the CLI Docker image"

[tasks.registry-login]
description = "Log in to Docker registry"
env = { REGISTRY_PASSWORD = { required = true }, REGISTRY_URL = { required = true }, REGISTRY_USERNAME = { required = true } }
run = 'echo "${REGISTRY_PASSWORD}" | docker login "${REGISTRY_URL}" -u "${REGISTRY_USERNAME}" --password-stdin'

[tasks.push]
description = "Push Docker image to registry"
usage = 'arg "<tag>" var=#true var_min=1 help="Image tags to push"'
run = """
FULL_IMAGE="${REGISTRY_URL}/${REGISTRY_USERNAME}/${IMAGE_NAME}"
for tag in ${usage_tag}; do
  docker tag "${IMAGE_NAME}" "${FULL_IMAGE}:${tag}"
done
docker push -a "${FULL_IMAGE}"
"""
depends = ["registry-login"]

[tasks.build-push]
description = "Build and push Docker image to registry"
usage = 'arg "<tag>" var=#true default="$(git rev-parse --short HEAD)-local" help="Image tags to push"'
run = [{ task = "build" }, "mise run push ${usage_tag}"]

[tasks.cli]
description = "Run CLI"
run = "uv run python -m rp_to_strong_cli"

[tasks.export-hevy-local]
env = { HEVY_API_KEY = { required = true } }
run = "uv run python -m rp_to_strong_cli hevy export --type exercise-templates -o exports/hevy/exercises.json"

[tasks.export-hevy-s3]
env = { BUCKET_NAME = { required = true }, HEVY_API_KEY = { required = true } }
run = "uv run python -m rp_to_strong_cli hevy export --type exercise-templates --output s3://$BUCKET_NAME/exports/exercises/hevy-exercises.json"

[tasks.export-rp-local]
run = "uv run python -m rp_to_strong_cli rp export --all --output exports/rp"

[tasks.export-rp-s3]
env = { BUCKET_NAME = { required = true } }
run = "uv run python -m rp_to_strong_cli rp export --type all --output s3://$BUCKET_NAME/exports/exercises/rp-exercises.json"
