[env]
RP_APP_BASE_URL = "https://training.rpstrength.com/api"
HEVY_API_BASE_URL = "https://api.hevyapp.com"

RP_APP_VERSION = "1.1.13"


[tasks.build]
run = "GITHUB_TOKEN=${GITHUB_TOKEN:-$(gh auth token)} docker build --secret id=GITHUB_TOKEN,env=GITHUB_TOKEN -f Dockerfile -t rp-to-strong-cli ../.."
description = "Build the CLI Docker image"

[tasks.cli]
description = "Run CLI"
run = "uv run python -m rp_to_strong_cli"

[tasks.export-hevy-local]
env = { HEVY_API_KEY = { required = true } }
run = "uv run python -m rp_to_strong_cli hevy export --type exercise-templates -o exports/hevy/exercises.json"

[tasks.export-hevy-s3]
env = { BUCKET_NAME = { required = true }, HEVY_API_KEY = { required = true } }
run = "uv run python -m rp_to_strong_cli hevy export --type exercise-templates --output s3://$BUCKET_NAME/exports/exercises/hevy-exercises.json"

[tasks.export-rp-local]
run = "uv run python -m rp_to_strong_cli rp export --all --output exports/rp"

[tasks.export-rp-s3]
env = { BUCKET_NAME = { required = true } }
run = "uv run python -m rp_to_strong_cli rp export --type all --output s3://$BUCKET_NAME/exports/exercises/rp-exercises.json"
