id: hevy_file_change_s3
namespace: rp_to_hevy.hevy

tasks:
  - id: execute_bash
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - echo "S3 file change detected in bucket {{ envs.bucket_name }}"

triggers:
  - id: s3_changes
    type: io.kestra.plugin.aws.s3.Trigger
    bucket: rp-to-hevy-data
    action: NONE
    prefix: exports/exercises
    on: CREATE_OR_UPDATE
    interval: PT10S
    logLevel: WARN
    failOnTriggerError: true
    logToFile: false

concurrency:
  limit: 1
