kestra:
  ai:
    type: "gemini"
    gemini:
      model-name: gemini-3-flash-preview

  server:
    basic-auth:
      username: "wadhah.mahroug15@gmail.com"
      password: "s/VewFv3L8Yg8N5m"
  tutorial-flows:
    enabled: false

micronaut:
  io:
    watch:
      enabled: true
      paths:
        - /app/flows