name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2404-arm
    name: build
    strategy:
      matrix:
        project: [cli]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
      - uses: useblacksmith/setup-docker-builder@ef12d5b165b596e3aa44ea8198d8fde563eab402 # v1.4.0
      - name: build-push
        working-directory: packages/${{ matrix.project }}
        run: mise run build-push $GIT_SHA_SHORT $GIT_BRANCH_NORM
        env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          GITHUB_TOKEN: ${{ github.token }}
