name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    env:
      MISE_AUTO_INSTALL: false
    strategy:
      matrix:
        project: [cli]
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Cache mise tools
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.local/share/mise
          key: mise-build-${{ matrix.project }}-${{ hashFiles('**/.mise.toml', '.mise.*.toml', '.miserc.toml') }}
          restore-keys: mise-build-${{ matrix.project }}-
      - uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d # v3.6.2
        with:
          install: false
          cache: false
          version: 2026.3.0
      - name: Tailscale
        uses: tailscale/github-action@53acf823325fe9ca47f4cdaa951f90b4b0de5bb9 # v4.1.1
        with:
          authkey: ${{ secrets.TALSCALE_KEY }}
      - name: Setup remote builder
        run: |
          docker buildx create \
            --name remote-builder \
            --driver remote \
            tcp://${{ secrets.REMOTE_BUILDER_ADDRESS }}:${{ secrets.REMOTE_BUILDER_PORT }}
          docker buildx use remote-builder
      - name: build
        run: mise //packages/${{ matrix.project }}:build
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # disabled for now until further work

# - name: build-push
#   working-directory: packages/${{ matrix.project }}
#   run: mise run build-push $GIT_SHA_SHORT $GIT_BRANCH_NORM
#   env:
#     REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
#     REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
#     REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
#     GITHUB_TOKEN: ${{ github.token }}
